[common]
# these are /48 allocations
ula = "fda2:d982:1da2"
gua = "2001:470:b1bb"
# this is a /16
v4 = "10.77.0.0"

[networks.cloud]
ula = "180d"
v4 = "10.77.3.0"

[networks.hexagone]
ula = "ed22"
v4 = "10.77.2.0"

[networks.roadwarrior]
ula = "a88b"
v4 = "10.77.1.0"

[networks.fake]
ula = "c93a"
v4 = "10.77.127.0"

# fake machines that use netstack
[hosts.httpserver]
network = "fake"

[hosts.httpserver.wireguard]
pubkey = "kKVzfevjDxgFEFpmexEiJqgL5x6OMV9B0EUiUWjo7Bc="
addrs = { v4 = "10.77.127.1", v6 = "c93a:8746:e81e:b9ec:0943" }

# roadwarrior machines that can move around

[hosts.la-tahorskami]
network = "roadwarrior"
tailscale = "100.90.200.5"

[hosts.la-selbeifonxa]
network = "roadwarrior"
tailscale = "100.125.113.109"

[hosts.genza]
network = "hexagone"
ip_addr = "192.168.2.24"

[hosts.genza.wireguard]
pubkey = "Q9QO+IsK5ISqdEnXm0EMovEXKSZ15J3ASlUaX7bZDm0="
port = 51822
addrs = { v4 = "10.77.1.4", v6 = "a88b:06c8:3903:be65:3261" }

# hexagone
[hosts.keanu]
network = "hexagone"
ip_addr = "192.168.0.158"
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGDZUmuhfjEIROo2hog2c8J53taRuPJLNOtdaT8Nt69W"

[hosts.keanu.wireguard]
pubkey = "Dh0D2bdtSmx1Udvuwh7BdWuCADsHEfgWy8usHc1SJkU="
port = 51822
addrs = { v4 = "10.77.2.1", v6 = "ed22:c815:3632:42fc:a1d2" }

[hosts.chrysalis]
network = "hexagone"
ip_addr = "192.168.2.29"
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGDA5iXvkKyvAiMEd/5IruwKwoymC8WxH4tLcLWOSYJ1"
tailscale = "100.97.53.92"

[hosts.chrysalis.wireguard]
pubkey = "Um46toyF9DPeyQWmy4nyyxJH/m37HWXcX+ncJa3Mg0A="
port = 51822
addrs = { v4 = "10.77.2.2", v6 = "ed22:9064:6df9:4855:611d" }

[hosts.shachi]
network = "hexagone"
ip_addr = "192.168.2.14"
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL3Jt26HXD7mLNjg+B+pB5+fXtxEmMeR6Bqv1Z5/819n"
tailscale = "100.67.184.57"

[hosts.shachi.wireguard]
pubkey = "S8XgS18Z8xiKwed6wu9FE/JEp1a/tFRemSgfUl3JPFw="
port = 51820
addrs = { v4 = "10.77.2.8", v6 = "ed22:a601:31ef:e676:e9bd" } 

# cloud machines
[hosts.lufta]
network = "cloud"
ip_addr = "135.181.162.99"
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMADhGV0hKt3ZY+uBjgOXX08txBS6MmHZcSL61KAd3df"
tailscale = "100.108.231.33"

[hosts.lufta.wireguard]
pubkey = "GJMOmAHUXQ7NfAMuEKQ7zhMmd1TIuJKKGYiC8hVpgEU="
port = 51822
addrs = { v4 = "10.77.3.1", v6 = "180d:b7a4:9c5c:989b:ba02" }

[hosts.firgu]
network = "cloud"
ip_addr = "149.248.59.1"
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB8+mCR+MEsv0XYi7ohvdKLbDecBtb3uKGQOPfIhdj3C"

[hosts.firgu.wireguard]
pubkey = "iGQ40ldOoV4QzLdvlzsTzaQxI4cmVMz1fguPoN44swU="
port = 51822
addrs = { v4 = "10.77.3.2", v6 = "180d:8b49:c521:5fb2:5e55" }

[hosts.kahless]
network = "cloud"
ip_addr = "198.27.67.207"
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFpymIxDxOBu6wWD4mgJ+lPbh3vgHrFg3tEDZqYCteDS"

[hosts.kahless.wireguard]
pubkey = "Bq70QQWxC/W6oQrBPcsXS1W7AP9hPS7gpkHPCLc2030="
port = 51820
addrs = { v4 = "10.77.3.3", v6 = "180d:ce10:049d:742d:aab7" }
