[common]
# these are /48 allocations
ula = "fda2:d982:1da2"
gua = "2001:470:b1bb"
# this is a /16
v4 = "10.77.0.0"

[networks.cloud]
ula = "180d"
v4 = "10.77.3.0"

[networks.avalon]
ula = "ed22"
v4 = "10.77.2.0"

[networks.roadwarrior]
ula = "a88b"
v4 = "10.77.1.0"

[networks.fake]
ula = "c93a"
v4 = "10.77.127.0"

[networks.kos-mos]
ula = "278a"
v4 = "10.77.128.0"

[networks.logos]
ula = "5fd9"
v4 = "10.77.129.0"

[networks.ontos]
ula = "1562"
v4 = "10.77.130.0"

[networks.pneuma]
ula = "bb17"
v4 = "10.77.131.0"

[networks.itsuki]
ula = "79f2"
v4 = "10.77.132.0"

# fake machines that use netstack
[hosts.httpserver]
network = "fake"

[hosts.httpserver.wireguard]
pubkey = "kKVzfevjDxgFEFpmexEiJqgL5x6OMV9B0EUiUWjo7Bc="
addrs = { v4 = "10.77.127.1", v6 = "c93a:8746:e81e:b9ec:0943" }

[hosts.genza]
network = "avalon"
ip_addr = "192.168.2.24"

[hosts.genza.wireguard]
pubkey = "Q9QO+IsK5ISqdEnXm0EMovEXKSZ15J3ASlUaX7bZDm0="
port = 51822
addrs = { v4 = "10.77.1.4", v6 = "a88b:06c8:3903:be65:3261" }

# avalon

[hosts.itsuki]
network = "avalon"
ip_addr = "192.168.2.174"
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP0eD0K2FqhkkIsUrYfmHigwbaUgOSotdSsNlLMRJiqx"
tailscale = "100.100.2.1"

[hosts.istuki.wireguard]
pubkey = "lazlobf9iG07HXEeFOf2WNjw4xz13iGI5SMp50+MZ0U="
port = 51823
addrs = { v4 = "10.77.2.40", v6 = "ed22:ad46:b73c:2e67:8f7f" }
#extra_addrs = [ "10.77.128.0/24", "2001:470:b1bb:278a::/64", "fda2:d982:1da2:278a::/64" ]

[hosts.kos-mos]
network = "avalon"
ip_addr = "192.168.2.32"
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINT+TxO1wYtifFcd7b5+asgImZb5ReLV1dTj6C2qgKzK"
tailscale = "100.122.181.67"

[hosts.kos-mos.solanum]
sid = "128"
description = "Battle systems set to close quarters combat"

[hosts.kos-mos.wireguard]
pubkey = "I9FhXd/V5mnbpt+3X9Ujr/Rf32pSyerExySPe+ATky4="
port = 51823
addrs = { v4 = "10.77.2.20", v6 = "ed22:33c2:b50a:e0bd:964d" }
#extra_addrs = [ "10.77.128.0/24", "2001:470:b1bb:278a::/64", "fda2:d982:1da2:278a::/64" ]

[hosts.logos]
network = "avalon"
ip_addr = "192.168.2.35"
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO0KXXcAdzVVwjEjRCUahsRYyFxjMCpgbLf48LUKWWBC"
tailscale = "100.96.184.60"

[hosts.logos.solanum]
sid = "129"
description = "Time to take out the trash!"

[hosts.logos.wireguard]
pubkey = "UzS3LhPwDDW2AjeYP9I6r1ZOtm+RTf2DbcnZn27CNyw="
port = 51824
addrs = { v4 = "10.77.2.21", v6 = "ed22:0a60:029e:327d:df92" }
#extra_addrs = [ "10.77.129.0/24", "2001:470:b1bb:5fd9::/64", "fda2:d982:1da2:5fd9::/64" ]

[hosts.ontos]
network = "avalon"
ip_addr = "192.168.2.34"
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGJ0MKlPgIfnS9T/sh57tz4pL5DND4RU7bXvhNCLo+8g"
tailscale = "100.103.116.84"

[hosts.ontos.solanum]
sid = "130"
description = "Feel my power!"

[hosts.ontos.wireguard]
pubkey = "IB6doRynP7Uzc5/HJykS3ijMlR1TNJ4AUtyLAW4KBkg="
port = 51825
addrs = { v4 = "10.77.2.22", v6 = "ed22:d052:8b54:cc73:c673" }
#extra_addrs = [ "10.77.130.0/24", "2001:470:b1bb:1562::/64", "fda2:d982:1da2:1562::/64" ]

[hosts.pneuma]
network = "avalon"
ip_addr = "192.168.2.33"
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFMYB+fI24NlIA+Zc7G/3whu8vK4+EdGKkygrE++zTXq"
tailscale = "100.78.40.86"

[hosts.pneuma.solanum]
sid = "131"
description = "I am lost no longer"

[hosts.pneuma.wireguard]
pubkey = "0UEMluK05tjDU5buPMIewZbHIB93JHQH4fmx9tdZ6yY="
port = 51825
addrs = { v4 = "10.77.2.23", v6 = "ed22:eba3:7f7d:281a:a132" }
#extra_addrs = [ "10.77.131.0/24", "2001:470:b1bb:1562::/64", "fda2:d982:1da2:1562::/64" ]

[hosts.keanu]
network = "avalon"
ip_addr = "192.168.0.158"
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGDZUmuhfjEIROo2hog2c8J53taRuPJLNOtdaT8Nt69W"

[hosts.keanu.wireguard]
pubkey = "Dh0D2bdtSmx1Udvuwh7BdWuCADsHEfgWy8usHc1SJkU="
port = 51822
addrs = { v4 = "10.77.2.1", v6 = "ed22:c815:3632:42fc:a1d2" }

[hosts.chrysalis]
network = "avalon"
ip_addr = "192.168.2.29"
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGDA5iXvkKyvAiMEd/5IruwKwoymC8WxH4tLcLWOSYJ1"
tailscale = "100.97.53.92"

[hosts.chrysalis.wireguard]
pubkey = "Um46toyF9DPeyQWmy4nyyxJH/m37HWXcX+ncJa3Mg0A="
port = 51822
addrs = { v4 = "10.77.2.2", v6 = "ed22:9064:6df9:4855:611d" }

[hosts.shachi]
network = "avalon"
ip_addr = "192.168.2.14"
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL3Jt26HXD7mLNjg+B+pB5+fXtxEmMeR6Bqv1Z5/819n"
tailscale = "100.87.242.16"

[hosts.shachi.wireguard]
pubkey = "S8XgS18Z8xiKwed6wu9FE/JEp1a/tFRemSgfUl3JPFw="
port = 51820
addrs = { v4 = "10.77.2.8", v6 = "ed22:a601:31ef:e676:e9bd" } 

# cloud machines
[hosts.lufta]
network = "cloud"
ip_addr = "135.181.162.99"
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMADhGV0hKt3ZY+uBjgOXX08txBS6MmHZcSL61KAd3df"
tailscale = "100.103.44.76"

[hosts.lufta.wireguard]
pubkey = "GJMOmAHUXQ7NfAMuEKQ7zhMmd1TIuJKKGYiC8hVpgEU="
port = 51822
addrs = { v4 = "10.77.3.1", v6 = "180d:b7a4:9c5c:989b:ba02" }

[hosts.firgu]
network = "cloud"
ip_addr = "149.248.59.1"
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB8+mCR+MEsv0XYi7ohvdKLbDecBtb3uKGQOPfIhdj3C"

[hosts.firgu.wireguard]
pubkey = "iGQ40ldOoV4QzLdvlzsTzaQxI4cmVMz1fguPoN44swU="
port = 51822
addrs = { v4 = "10.77.3.2", v6 = "180d:8b49:c521:5fb2:5e55" }

[hosts.kahless]
network = "cloud"
ip_addr = "198.27.67.207"
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFpymIxDxOBu6wWD4mgJ+lPbh3vgHrFg3tEDZqYCteDS"

[hosts.kahless.wireguard]
pubkey = "Bq70QQWxC/W6oQrBPcsXS1W7AP9hPS7gpkHPCLc2030="
port = 51820
addrs = { v4 = "10.77.3.3", v6 = "180d:ce10:049d:742d:aab7" }
