[common]
# these are /48 allocations
ula = "fda2:d982:1da2"
gua = "2001:470:b1bb"
# this is a /16
v4 = "10.77.0.0"

[networks.cloud]
ula = "180d"
v4 = "10.77.3.0"

[networks.avalon]
ula = "ed22"
v4 = "10.77.2.0"

[networks.roadwarrior]
ula = "a88b"
v4 = "10.77.1.0"

[networks.fake]
ula = "c93a"
v4 = "10.77.127.0"

[networks.kos-mos]
ula = "278a"
v4 = "10.77.128.0"

[networks.logos]
ula = "5fd9"
v4 = "10.77.129.0"

[networks.ontos]
ula = "1562"
v4 = "10.77.130.0"

[networks.pneuma]
ula = "bb17"
v4 = "10.77.131.0"

[networks.itsuki]
ula = "79f2"
v4 = "10.77.134.0"

[hosts.genza]
network = "avalon"
ip_addr = "192.168.2.24"

# avalon

[hosts.itsuki]
network = "avalon"
ip_addr = "192.168.2.174"
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP0eD0K2FqhkkIsUrYfmHigwbaUgOSotdSsNlLMRJiqx"
tailscale = "100.68.185.47"

[hosts.kos-mos]
network = "avalon"
ip_addr = "192.168.2.32"
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINT+TxO1wYtifFcd7b5+asgImZb5ReLV1dTj6C2qgKzK"
tailscale = "100.122.181.67"

[hosts.kos-mos.solanum]
sid = "128"
description = "Battle systems set to close quarters combat"

[hosts.logos]
network = "avalon"
ip_addr = "192.168.2.35"
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO0KXXcAdzVVwjEjRCUahsRYyFxjMCpgbLf48LUKWWBC"
tailscale = "100.96.184.60"

[hosts.logos.solanum]
sid = "129"
description = "Time to take out the trash!"

[hosts.ontos]
network = "avalon"
ip_addr = "192.168.2.34"
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGJ0MKlPgIfnS9T/sh57tz4pL5DND4RU7bXvhNCLo+8g"
tailscale = "100.103.116.84"

[hosts.ontos.solanum]
sid = "130"
description = "Feel my power!"

[hosts.pneuma]
network = "avalon"
ip_addr = "192.168.2.33"
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFMYB+fI24NlIA+Zc7G/3whu8vK4+EdGKkygrE++zTXq"
tailscale = "100.78.40.86"

[hosts.pneuma.solanum]
sid = "131"
description = "I am lost no longer"

[hosts.keanu]
network = "avalon"
ip_addr = "192.168.0.158"
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGDZUmuhfjEIROo2hog2c8J53taRuPJLNOtdaT8Nt69W"

[hosts.chrysalis]
network = "avalon"
ip_addr = "192.168.2.29"
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGDA5iXvkKyvAiMEd/5IruwKwoymC8WxH4tLcLWOSYJ1"
tailscale = "100.97.53.92"

[hosts.shachi]
network = "avalon"
ip_addr = "192.168.2.14"
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL3Jt26HXD7mLNjg+B+pB5+fXtxEmMeR6Bqv1Z5/819n"
tailscale = "100.87.242.16"

# cloud machines
[hosts.lufta]
network = "cloud"
ip_addr = "135.181.162.99"
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMADhGV0hKt3ZY+uBjgOXX08txBS6MmHZcSL61KAd3df"
tailscale = "100.103.44.76"

[hosts.firgu]
network = "cloud"
ip_addr = "149.248.59.1"
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB8+mCR+MEsv0XYi7ohvdKLbDecBtb3uKGQOPfIhdj3C"

[hosts.kahless]
network = "cloud"
ip_addr = "198.27.67.207"
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFpymIxDxOBu6wWD4mgJ+lPbh3vgHrFg3tEDZqYCteDS"
