[common]
# these are /48 allocations
ula = "fda2:d982:1da2"
gua = "2001:470:b1bb"
# this is a /16
v4 = "10.77.0.0"

[networks.cloud]
ula = "180d"
v4 = "10.77.3.0"

[networks.hexagone]
ula = "ed22"
v4 = "10.77.2.0"

[networks.roadwarrior]
ula = "a88b"
v4 = "10.77.1.0"

# roadwarrior machines that can move around

[hosts.la-tahorskami]
network = "roadwarrior"

[hosts.la-tahorskami.wireguard]
pubkey = "d/0BCLjiJjxftyBrEOSoxUhz2FHxvKwgOA/hX73NpQ8="
addrs = { v4 = "10.77.1.1", v6 = "a88b:0cd3:739c:9308:8c73" }

[hosts.la-selbeifonxa]
network = "roadwarrior"

[hosts.la-selbeifonxa.wireguard]
pubkey = "2eu4fh8STQDB1aeFP9C7nRyeOmw3k2ba/WpEBPJ5wmc="
addrs = { v4 = "10.77.1.2", v6 = "a88b:6890:96a1:a25b:d0c3" }

[hosts.tolsutra]
network = "roadwarrior"

[hosts.tolsutra.wireguard]
pubkey = "tDQlTm35G9LT9GE+VX1gWgnd2i9dmsmC6hSnTjiOBXM="
addrs = { v4 = "10.77.1.3", v6 = "a88b:771c:4af8:b5c3:d2e1" }

# hexagone
[hosts.keanu]
network = "hexagone"
ip_addr = "192.168.0.159"

[hosts.keanu.wireguard]
pubkey = "Dh0D2bdtSmx1Udvuwh7BdWuCADsHEfgWy8usHc1SJkU="
port = 51822
addrs = { v4 = "10.77.2.1", v6 = "ed22:c815:3632:42fc:a1d2" }

[hosts.chrysalis]
network = "hexagone"
ip_addr = "192.168.0.127"

[hosts.chrysalis.wireguard]
pubkey = "Um46toyF9DPeyQWmy4nyyxJH/m37HWXcX+ncJa3Mg0A="
port = 51822
addrs = { v4 = "10.77.2.2", v6 = "ed22:9064:6df9:4855:611d" }

# cloud machines
[hosts.lufta]
network = "cloud"
ip_addr = "135.181.162.99"

[hosts.lufta.wireguard]
pubkey = "GJMOmAHUXQ7NfAMuEKQ7zhMmd1TIuJKKGYiC8hVpgEU="
port = 51822
addrs = { v4 = "10.77.3.1", v6 = "180d:b7a4:9c5c:989b:ba02" }

[hosts.firgu]
network = "cloud"
ip_addr = "149.248.59.1"

[hosts.firgu.wireguard]
pubkey = "iGQ40ldOoV4QzLdvlzsTzaQxI4cmVMz1fguPoN44swU="
port = 51822
addrs = { v4 = "10.77.3.2", v6 = "180d:8b49:c521:5fb2:5e55" }